title: Product Management Basics Certification
uri: https://www.credly.com/badges/377f6224-5c1c-44c8-abf3-f2051b972f61/linked_in_profile
organisationId: pendo
type: training
date: 2023-11-01T00:00:00+0000
